ALTER TABLE "StoreOrderItem" ADD COLUMN IF NOT EXISTS "isPurchased" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "StoreOrderItem" ADD COLUMN IF NOT EXISTS "quantityPurchased" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "StoreOrderItem" ADD COLUMN IF NOT EXISTS "imageUrl" TEXT;
